### ISSUE TITLE
reads vs fragments in metrics documentation

### ISSUE THREAD

**Issue by julienlag** [Flomics/rnaseq-FlomicsQC-manual#2]
double-check if metrics refer to sequencing _reads_ or _fragments_, and fix documentation accordingly (currently here 
https://docs.google.com/spreadsheets/d/1Lxt-A_7Zullm_szqtyB5o0tgTCH4BdyhsjJ1MSXwcuU/edit#gid=1185880933 )

**Comment by lcabus-flomics** [comment]
They refer to fragments, not reads. I have fixed the documentation accordingly
